language: ruby
cache:
  bundler: true
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
before_install:
  - yes | gem update --force --system
  - gem install bundler
script:
  - bundle exec rake test
