name: ci

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        # - https://www.ruby-lang.org/en/downloads/branches
        ruby-version: [ '3.1', '3.2', '3.3', 'ruby-head' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # - https://github.com/ruby/setup-ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: '2.5'
        bundler-cache: true

    - name: Run tests
      run: |
        unset GST
        bundle exec rake test

    - name: Run tests w/ older Psych gems
      run: |
        GST=1 bundle update && bundle exec rake test
        GST=2 bundle update && bundle exec rake test
        GST=3 bundle update && bundle exec rake test
