name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest','macos-latest' ]
        # - https://www.ruby-lang.org/en/downloads/branches
        ruby-version: [ 'head','3.4','3.3','3.2' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # - https://github.com/ruby/setup-ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: 'latest'
        bundler-cache: true
        #cache-version: 1

    - name: Run tests
      run: |
        unset GST
        bundle exec rake test

    - name: Run tests w/ older Psych gems
      run: |
        GST=1 bundle update && bundle exec rake test
        GST=2 bundle update && bundle exec rake test
        GST=3 bundle update && bundle exec rake test
